import Link from 'next/link';

import { Background } from '../background/Background';
import { HeroTitle } from '../hero/HeroTitle';
import { Section } from '../layout/Section';
import { Logo } from './Logo';
import { NeedMoreDataModal } from '../modal/NeedMoreDataModal';
import { CategorySelectionTab } from '@/tab/CategorySelectionTab';

type Category = {
  name: string;
  tools: Array<string>;
}

const categories: Array<Category> = [
  {name:"Productivity", tools:["Slack", "Email", "Messenger"]},
  {name:"Operation", tools:["Customer Service", "Human Resource", "Sales"]},
  {name:"Engineering", tools:["Logging", "Tickets", "Code"]},
  {name:"E-commerce", tools:["Shopping Data", "Delivery Data"]},
  {name:"Finance", tools:["Trading Data"]},
]

const Hero = () => (
  <Background color="bg-gray-100">
    <Section yPadding="py-6">
      <div className="flex flex-wrap items-center justify-between">
        <div>
          <Link href="/"><Logo xl /></Link>
        </div>
      </div>
    </Section>

    <Section yPadding="pt-20">
      <HeroTitle
        title={
          <>
            {'Get your "hard-to-get" mock data with\n'}
            <span className="text-primary-500">MockPolar AI</span>
          </>
        }
        description="The data is generated by GenAI."
      />
    </Section>
    <Section>
      <div className="text-center">
        <div className="whitespace-pre-line text-4xl font-bold text-gray-900">
          <CategorySelectionTab categories={categories}/>
        </div>
        <div className="pt-20">
          <NeedMoreDataModal />
        </div>
      </div>
    </Section>
  </Background>
)


export { Hero };
