import Link from 'next/link';
import * as React from 'react';
import Grid from '@mui/material/Grid';

import { Background } from '../background/Background';
import { HeroTitle } from '../hero/HeroTitle';
import { Section } from '../layout/Section';
import { Logo } from './Logo';
import { CodeSnippet } from './CodeSnippet';
import { NeedMoreDataModal } from '../modal/NeedMoreDataModal';
import { DataRequestModal } from '../modal/DataRequestModal';
import { CategorySelectionTab } from '@/tab/CategorySelectionTab';
import { red, orange, blue } from '@mui/material/colors';

type Categories = {
  name: string;
}

const industries: Array<Categories> = [
  {name:"Shopping"},
  {name:"Contents subscription"},
  {name:"Travel"},
  {name:"Delivery"},
  {name:"B2B SaaS"},
  {name:"Productivity"},
]

const tools: Array<Categories> = [
  {name:"Zendesk"},
  {name:"Email"},
  {name:"FreshDesk"},
  {name:"Intercom"},
  {name:"Kakaotalk"},
]

const windows: Array<Categories> = [
  {name:"1 Day"},
  {name:"3 Days"},
  {name:"1 Week"},
  {name:"2 Week"},
  {name:"1 Month"},
  {name:"3 Month"},
]

const Hero = () => {
  
  const [industry, setIndustry] = React.useState(0);
  const [tool, setTool] = React.useState(0);
  const [window, setWindow] = React.useState(0);

  const getCode = () => {
    const code = [
      {
        "industry": industries[industry]?.name ,
        "output format": tools[tool]?.name,
        "time window": windows[window]?.name ,
      },
    ]
    return code
  };

  return (
      <Background color="bg-gray-100">
        <Section yPadding="py-6">
          <div className="flex flex-wrap items-center justify-between">
            <div>
              <Link href="/"><Logo xl /></Link>
            </div>
          </div>
        </Section>

        <Section yPadding="pt-20">
          <HeroTitle
            title={
              <>
                {'Get your "hard-to-get" mock data with\n'}
                <span className="text-primary-500">MockPolar AI</span>
              </>
            }
            description="The data is generated by GenAI."
          />
        </Section>
        <Section>
          <div className="text-center">
            <div className="mb-4 text-xl">Explore various mock customer service data as an example.</div>
            <div className="whitespace-pre-line text-4xl font-bold text-gray-900">
              <Grid container spacing={1}>
                <Grid item xs={3} md={2}>
                  <div className='text-sm flex h-full justify-end items-center pr-2'>Industry</div>
                </Grid>
                <Grid item xs={9} md={10}>
                  <CategorySelectionTab categories={industries} selectedCategory={industry} setCategory={setIndustry} color={red[400]}/>
                </Grid>
              </Grid>
            </div>
            <div className="whitespace-pre-line text-4xl font-bold text-gray-900">
              <Grid container spacing={1}>
                <Grid item xs={3} md={2}>
                  <div className='text-sm flex h-full justify-end items-center pr-2'>Output Format</div>
                </Grid>
                <Grid item xs={9} md={10}>
                  <CategorySelectionTab categories={tools} selectedCategory={tool} setCategory={setTool} color={orange[600]}/>
                </Grid>
              </Grid>
            </div>
            <div className="whitespace-pre-line text-4xl font-bold text-gray-900">
              <Grid container spacing={1}>
                <Grid item xs={3} md={2}>
                  <div className='text-sm flex h-full justify-end items-center pr-2'>Time Window</div>
                </Grid>
                <Grid item xs={9} md={10}>
                  <CategorySelectionTab categories={windows} selectedCategory={window} setCategory={setWindow} color={blue[600]}/>
                </Grid>
              </Grid>
            </div>
          </div>
          <div className="mt-4 mb-4">
            <CodeSnippet code={getCode()}/>
          </div>
          <div className="text-center">
            <DataRequestModal selectedIndustry={industries[industry]?.name} selectedTool={tools[tool]?.name} selectedWindow={windows[window]?.name} />
          </div>
          <div className="text-center">
            <div className="mt-20 mb-4 text-xl">Of course! We have more. not only customer service data, but all kinds of others!</div>
            <NeedMoreDataModal />
          </div>
        </Section>
      </Background>
    )
}


export { Hero };
